- name: Create VM from template
  hosts: all

  vars:
     ansible_python_interpreter: /usr/bin/python3.9

  gather_facts: no
  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        name: kerem-test-vm
        template: kerem   
        datacenter: Konsalt-MESA
        datastore: EMC_VNX5700_LUN2
        folder: Ansible
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'   
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        networks:
        - name: VM Network
          ip: 192.168.0.99
          netmask: 255.255.0.0
          gateway: 192.168.0.1
          dns_servers:
            - 8.8.8.8
            
        state: poweredon