---
- name: Create VM from template
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

    datacenter: "Konsalt-MESA"
    datastore: "EMC_VNX5700_LUN2"
    template: "rhel-9-latest"
    folder: "Ansible"

    vm_name: "vm-test1"

    network_name: "VM Network"
    vm_ip: "192.168.90.57"
    netmask: "255.255.0.0"
    gateway: "192.168.0.1"

    dns_servers:
      - "8.8.8.8"

  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        validate_certs: false

        name: "{{ vm_name }}"
        template: "{{ template }}"
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        folder: "{{ folder }}"

        networks:
          - name: "{{ network_name }}"
            ip: "{{ vm_ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            dns_servers: "{{ dns_servers }}"

        state: poweredon
